feat(member expansion)
itsme-to/ItsMyBot pull request #8
Opened 2024-12-28 23:46 UTC by YourMCGeek

Add additional placeholders relating specifically to GuildMember, notably for booster, status, and server profiles

2024-12-31 15:08 UTC, itsme-to requested changes
Avoid return undefined by returning default value like, N/A, default discord avatar like the user variable or similar

2024-12-31 17:24 UTC, YourMCGeek commented
Changed some logic around for better returns and refactored some of the placeholder names. 

Should be good for your review.

2025-01-01 17:14 UTC, vic256 commented on src/core/services/expansions/impl/member.ts
> +                return context.member.avatarURL({ forceStatic: true }) || context.member.user.displayAvatarURL();
Is there any reason to use this instead of ``context.member.displayAvatarURL()`` ([docs](https://discord.js.org/docs/packages/discord.js/14.16.3/GuildMember:Class#displayAvatarURL)) ?

2025-01-02 04:17 UTC, YourMCGeek commented on src/core/services/expansions/impl/member.ts
> +                return context.member.avatarURL({ forceStatic: true }) || context.member.user.displayAvatarURL();
I don't really know of any benefit, no. It's just what I have used in the past, so the habit got the best of me. Will push a fix.

2025-01-04 01:13 UTC, merged